
trigger:
    batch: true
    branches:
        include:
            - master
pr: none

variables:
    system.debug: true

name: 1.0.$(Rev:r)

stages:
    - stage: Build
      displayName: Build
      pool:
        name: Ubuntu Pool
        vmImage: 'ubuntu-latest'
        demands: npm
      jobs:
        - job: compile
          steps:
              - checkout: self
                clean: true
                presistCredentials: true
              - bash: echo "##[debug]BEGIN"
              - task: NodeTool@0
                displayName: 'Use Node 16 LTS'
                inputs:
                   versionSpec: '16.13.1'
              - task: Npm@1
                displayName: 'npm install'
                inputs:
                    command: ci
                    verbose: false
                timeoutInMinutes: 5
              - bash: echo "##[debug]END"

    - stage: Package
      displayName: Package
      pool:
          vmImage: 'ubuntu-latest'
      jobs:
          - job: package
            steps:
                - bash: echo "##[debug]BEGIN"
                - bash: echo "##[debug]END"

    - stage: Deploy
      displayName: Deploy
      pool:
          vmImage: 'ubuntu-latest'
      jobs:
          - job: deploy
            steps:
                - bash: echo "##[debug]BEGIN"
                - bash: echo "##[debug]END"


