
trigger:
    batch: true
    branches:
        include:
            - master
pr: none

variables:
    system.debug: true

name: 1.0.$(Rev:r)

stages:
    - stage: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
        demands: npm
      jobs:
        - job: compile
          steps:
          - checkout: self
            clean: true
            persistCredentials: true
            fetchDepth: 1
          - task: NodeTool@0
            displayName: 'Use Node 16 LTS'
            inputs:
               versionSpec: '16.13.1'
          - task: Npm@1
            displayName: 'npm install'
            inputs:
                command: ci
                verbose: false
            timeoutInMinutes: 5

    - stage: Package
      displayName: Package
      pool:
          vmImage: 'ubuntu-latest'
      jobs:
          - job: package
            steps:
            - checkout: none
            - task: ArchiveFiles@2
              inputs:
                rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
                includeRootFoulder: false
            - task: PublishPipelineArtifact@0
              inputs:
                targetPath: '$(System.ArtifactsDirectory)'

    - stage: Deploy
      displayName: Deploy
      pool:
          vmImage: 'ubuntu-latest'
      jobs:
          - job: deploy
            steps:
            - checkout: none
            - task: DownloadPipelineArtifact@1
              inputs:
                downloadPath: '$(System.DefaultWorkingDirectory)'
            - bash: ls -al $(System.DefaultWorkingDirectory)/*
            - task: GithubRelease@1
              displayName: 'Create GitHub Release'
              inputs:
                  gitHubConnection: github.com_bdylanwalker
                  repositoryName: bdylanwalker/test-pipeline
                  tagSource: userSpecifiedTag
                  tag: release-$(Build.BuildNumber)
                  assets: $(System.DefaultWorkingDirectory)/drop/*.zip


